name: Trigger main repository to build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger
        run: |
          curl -X POST \
            https://api.github.com/repos/openedv/openedv-wiki/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GH_TOKEN }}' \
            -d '{"event_type":"build"}'
